<?php

// SICKHEAD PROPRIETARY INFORMATION
//
// This software is supplied under the terms of a license agreement 
// or nondisclosure agreement and may not be copied or disclosed 
// except in accordance with the terms of that agreement.
//
//  Copyright (c) Sickhead Games, LLC
//  All Rights Reserved
//  www.sickheadgames.com

$wallboard_config = array(

	// The url to your TeamCity server.
	"teamcity-url" => "http://your.teamcity.server.com/",
  
	// The username and password used to query the
	// TeamCity server for the current build state.
  "teamcity-login" => "username:password",
);

?>